### ISSUE TITLE
Plugin does not compile in Xcode Version 9.2 (9C40b)

### ISSUE THREAD

**Issue by arcadius** [3screens/cordova-brother-label-printer#34]
First of all, thank you very much @Ayiga and others for the great work on the original iOS plugin.

I have installed this plugin and it won't compile on Xcode Version 9.2 as it keeps complaining about `APPingModule.h`

Please see screenshot.

Is there any special config or setting that I need?

Many thanks.

![screenshot](https://user-images.githubusercontent.com/1615850/41570293-1302950a-7366-11e8-8fed-cb55bb92b86d.png)

**Comment by VictorCoding** [comment]
I had those compile errors as well, just comment them out. After you comment out those lines you'll get more compile errors, just keep commenting them out until it works. I ended up forking that branch so that I didn't have to do that everytime. I know it's not the best thing to do but I needed to get it up and running.

**Comment by arcadius** [comment]
Thanks @VictorCoding   for the tip :-)

**Comment by gordol** [comment]
> After you comment out those lines you'll get more compile errors, just keep commenting them out until it works.

*cringe*

I'm sorry all... I have not had time to maintain this thing lately... and I haven't even attempted to build or test the iOS fork, just trusted the community.

I'm moving soon, but I did find my label printer, and my old iPad, so I should be able to dust this thing off soon, in the coming month or so.

**Comment by rhohn94** [comment]
I can't get the plugin to compile, either. I get the same errors as arcadius. I can either comment them out or replace them with __Check_Compile_Time(), which also seems to work. But, after that, I get errors like this:

![screen shot 2018-07-29 at 8 09 54 am](https://user-images.githubusercontent.com/40176545/43366685-781f9044-9307-11e8-928e-6b4dd0064564.png)

It looks like I'm missing a library or something, but I have no experience with Objective C or Xcode, so I'm at a total loss here. I have confirmed that I only get these errors when I build with this plugin. If I remove it, the build works perfectly fine. I've tried a few of the different branches that have iOS support and they all yield the same errors.

**Comment by arcadius** [comment]
Hi @rhohn94 
The compilation issues among others are fixed in pull request 
https://github.com/gordol/cordova-brother-label-printer/pull/35
You can install that fix by following instructions in the top comment.
Thanks

**Comment by rhohn94** [comment]
@arcadius, thanks for the reply -- I'm trying with your fork now, but still get the Mach-O Linker error. I no longer get the check_compile_time errors, though. I am using Xcode version 9.4.1, if that's any help.

**Comment by arcadius** [comment]
@rhohn94 ... possibly uninstall the old plugin that does not compile... and make sure it's all gone before installing the new one.
After un-installing the old one, you may need to remove the ios platform and re-add it,
Then make sure it all compile and can run before you install the one from the pull request with:

`cordova plugin add https://github.com/MenelicSoftware/cordova-plugin-brother-label-printer#dev --save`

**Comment by gordol** [comment]
Indeed, with cordova/ionic you need to add/remove the platform after you make changes... at least, historically. Feel free to re-open this if y'all are still having issues.
